version: "3.1"

services:
  redis_container:
    image: redis:latest
    container_name: redis
    ports:
      - ${REDIS_BINDING_PORT}:${REDIS_PORT}
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_DEFAULT_CONFIG_FILE}:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_BINDING_PORT}:${POSTGRES_PORT}
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    restart: always
