spring:
  application:
    name: review
  profiles:
    active: dev
#  config:
#    import: "configserver:http://localhost:18080"
#    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 19097

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:19090/eureka/

#message: "default message" # config server? ???? ?? ?

#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh